### ISSUE TITLE
query returns all features

### ISSUE THREAD

**Issue by mapsgeek** [haoliangyu/koop-output-geojson#1]
i have provider file-geojson and the output geojson registered, the server works great with the default feature Services works great for all endpoints including queries in the following form
`query?where=SOVEREIGNT='Egypt'`
that works great with the endpoint 
`file-geojson/rest/services/country/FeatureServer/0/`

for output-geojson query doesn't work at all, it returns all features
i tried the following forms
`http://localhost:3000/file-geojson/country/geojson?where='SOVEREIGNT'=Egypt`
this as in the readme for the repo

i tried the same as the first query also but with the output-geojson endpoint all returns all features.
can you please provide a valid querying form that actually works ?

**Comment by mapsgeek** [comment]
to make things simpler i created this testing server with a simple geojson file called " count " as for the readme contains 3 points with field count.

here's the endpoint for the featureServer query, works just fine
http://koopserver.herokuapp.com/file-geojson/rest/services/count/FeatureServer/0/query?where=count=1

here's the endpoint for the output geojson query, returns all the 3 features
http://koopserver.herokuapp.com/file-geojson/count/geojson?where=count=1
http://koopserver.herokuapp.com/file-geojson/count/geojson?where='count'>2

neither works

**Comment by haoliangyu** [comment]
Thanks for reporting this issue. I have identified a bug in the request query parameters handling and fixed it at `v1.0.1`. Please update and check if the new version works for you.

**Comment by mapsgeek** [comment]
Yup works as expected, thank you
