### ISSUE TITLE
Cannot GET  /koop/es/rest/services/:host/:id/geojson

### ISSUE THREAD

**Issue by keithfraley** [haoliangyu/koop-output-geojson#2]
hello, I trying to work with your output provider using the elasticsearch provider.

It states when i start the provider:

"GeoJSON" output routes for the "es" provider  Methods  
---------------------------------------------  ---------
/es/:host/:id/geojson                          GET, POST
/es/:host/:id/topojson                         GET, POST

However. I get 

Cannot GET /koop/es/rest/services/:host/:id/geojson

When I try to pull the data

**Comment by haoliangyu** [comment]
@keithfraley This should have been fixed at the v1.1.2 version. Please let me know if the fix works for you.
